### ISSUE TITLE
Supplementary material of the DGCNN paper

### ISSUE THREAD

**Issue by eiiijiiiy** [muhanzhang/DGCNN#10]
Hello Dr. Zhang,

Thank you for this impressive work!

May you kindly share the supplementary materials mentioned in the paper?
It seems many versions of DGCNN don't contain that material.

Thanks a lot in advance for your kind help

**Comment by muhanzhang** [comment]
Hi! It is available on my website: https://muhanzhang.github.io/papers/AAAI_2018_DGCNN_appendix.pdf.

**Comment by eiiijiiiy** [comment]
Got it and many thanks!
