### ISSUE TITLE
where i can get the SI?

### ISSUE THREAD

**Issue by Calemsy** [muhanzhang/DGCNN#5]
It's a great job!
as you said in the paper, there are some details and information in the supplementary material, but the paper i download without the material, where i can get the them?

**Comment by muhanzhang** [comment]
Hi, thanks. You can find it in my website https://www.cse.wustl.edu/~muhan/papers/AAAI_2018_DGCNN_appendix.pdf

**Comment by Calemsy** [comment]
Thanks for your reply.
