### ISSUE TITLE
How to deal with different size of graph data?

### ISSUE THREAD

**Issue by Calemsy** [muhanzhang/DGCNN#6]
What i want to know is that the Graph Convolution Layer how to accept different size of graph data as input? For Example, In the data set `Mutag`, the nodes contains in each graph usually different, the nodes in `mutag_1.graph` and `mutag_2.graph` are 23 and 26, respectively, right?. How to deal with this?

**Comment by Calemsy** [comment]
I think maybe cause the lack of knowledge about the data "Mutag", all the graph in the "Mutag" has 28 nodes(but most of them are subset), so the size of Graph Convolution Layer has fixed. right?

**Comment by muhanzhang** [comment]
No. GNN naturally accept different-size graphs as input. Since graph convolution is local, it is invariant to graph sizes. The graph aggregation step will summarize the local graph convolution results into a graph-level feature vector.

**Comment by Calemsy** [comment]
This reply drag me back from the wrong path in time. Thank you.

And another question, hope is the last one, i want to ask for you is that in the part of ERRATA of supplementary material, you claimed "we set the k of SortPooling such that 90% graphs have nodes less than k in order to compensate the loss of node features.", I cannot figure out how to deal with the case when $n < k$ which is most more case under this setting. right?

**Comment by muhanzhang** [comment]
Hi, when $n<k$, we just append $k-n$ all-zero vectors to the $n$ sorted vectors to pad to length $k$.

**Comment by Calemsy** [comment]
> Hi, when n<k, we just append k−n all-zero vectors to the n sorted vectors to pad to length k.

Thank you!

**Comment by xp561** [comment]
but the size of output is different when the size of input is different, how do we use the same linear layer the adapt different size of output of GNN? appreciate a lot if u can help me
