### ISSUE TITLE
Question about build the X

### ISSUE THREAD

**Issue by Calemsy** [muhanzhang/DGCNN#8]
Hi~
If nodes in graph have different type(tag), how to build the matrix `X`. 
For example, one graph with 5 nodes and the tags of them are [0, 1, 1, 1, 2], and another one with 6 nodes and the tags are [0, 1, 1, 2, 3, 3](for sake of simplicity, assume only these two graphs in the dataset),  under such case, what is the initial channels `c` should be? 
Maybe the `c` equal to 4, so
[[1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]]
and 
[[1 0 0 0]
[0 1 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]
[0 0 0 1]]
are the `X` of first and second graph, respectively?

**Comment by muhanzhang** [comment]
Yes, you are right.

**Comment by Calemsy** [comment]
Thanks for your patient reply all the time.

**Comment by XuSShuai** [comment]
Is that the same in the SEAL? 
In your paper about SEAL, you proposed the  method called `Double-Radius Node Labeling` to labeling the nodes in each enclosing subgraph, after get the label, does still use the above way to construct `X`?
